### ISSUE TITLE
Хранить данные пользователей на сервере

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#177]
Для хранения структуры проектов можно использовать firebase.io + json | PostgreSQL by Heroku

Для хранения файлов можно использовать один из сервисов (дополнительно провести сравнительный анализ): Amazon S3, Heroku, ...

В рамках данной задачи необходимо:
* Подключить удаленный репозиторий к проекту
* Изменить классы репозиториев на взаимодействие с постоянным хранилищем
* Возможность задать реквизиты/конфигурацию постоянного хранилища.

> Мы не хотим хранить файлы в реляционной БД потому что:

>  - Файлы могут быть любого размера - это отрицательно скажется на производительности БД
>  - Поиск по контенту файлов в БД не будет производиться => избыточное хранение неиспользуемой информации

**Comment by lagroffe** [comment]
Решили пока использовать для хранения файлов файлохранилище Firebase, а для структуры пользователи/проекты/файлы - Postgres на Heroku

**Comment by adavydenko** [comment]
После обсуждения (06.07) решили остановиться только на firebase, при необходимости часть БД мигрируем позже на PostgresSQL.

Выделили следующие подзадачи:

1. Поддержка хранения файлов пользователей в чистом виде (raw files) - использовать Firebase file storage
- [ ] Завести аккаунат на Firebase (#211)
- [ ] Изменения FileInfo repository (#212)
  * Классы подключения к Firebase File Storage
  * Upload/Download files 
- [ ] Firebase FileStorage settings (#213)
  * классы конфигурации
  * добавить поддержку конфигурации в UI
1. Хранение распарсенных файлов - использовать Firebase Realtime database
- [ ] Разработать структуру ~БД Firebase Realtime Database
- [ ] Изменить существующие репозитории на хранение распарсенных файлов на Firebase + обеспечить передачу файлов в R скрипты
1. Хранение структуры проектов - использовать Firebase Realtime database
- [ ] Разработать структуру БД для хранения информации о проектах
- [ ] Реализовать сохранение данных о проектах в Firebase Realtime Database
1. Тестирование
- [ ] test fest
